/**
 * generated by Xtext 2.17.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.mopt;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mdeoptimiser.languages.mopt.MoptPackage
 * @generated
 */
public interface MoptFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MoptFactory eINSTANCE = uk.ac.kcl.inf.mdeoptimiser.languages.mopt.impl.MoptFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Optimisation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Optimisation</em>'.
   * @generated
   */
  Optimisation createOptimisation();

  /**
   * Returns a new object of class '<em>Problem Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Problem Spec</em>'.
   * @generated
   */
  ProblemSpec createProblemSpec();

  /**
   * Returns a new object of class '<em>Goal Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Goal Spec</em>'.
   * @generated
   */
  GoalSpec createGoalSpec();

  /**
   * Returns a new object of class '<em>Search Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Search Spec</em>'.
   * @generated
   */
  SearchSpec createSearchSpec();

  /**
   * Returns a new object of class '<em>Solver Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Solver Spec</em>'.
   * @generated
   */
  SolverSpec createSolverSpec();

  /**
   * Returns a new object of class '<em>Base Path Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Base Path Spec</em>'.
   * @generated
   */
  BasePathSpec createBasePathSpec();

  /**
   * Returns a new object of class '<em>Meta Model Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Meta Model Spec</em>'.
   * @generated
   */
  MetaModelSpec createMetaModelSpec();

  /**
   * Returns a new object of class '<em>Model Path Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Path Spec</em>'.
   * @generated
   */
  ModelPathSpec createModelPathSpec();

  /**
   * Returns a new object of class '<em>Objective Interpreter Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Objective Interpreter Spec</em>'.
   * @generated
   */
  ObjectiveInterpreterSpec createObjectiveInterpreterSpec();

  /**
   * Returns a new object of class '<em>Constraint Interpreter Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Interpreter Spec</em>'.
   * @generated
   */
  ConstraintInterpreterSpec createConstraintInterpreterSpec();

  /**
   * Returns a new object of class '<em>Model Initialiser Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Initialiser Spec</em>'.
   * @generated
   */
  ModelInitialiserSpec createModelInitialiserSpec();

  /**
   * Returns a new object of class '<em>Problem Part Specifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Problem Part Specifier</em>'.
   * @generated
   */
  ProblemPartSpecifier createProblemPartSpecifier();

  /**
   * Returns a new object of class '<em>Rulegen Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rulegen Spec</em>'.
   * @generated
   */
  RulegenSpec createRulegenSpec();

  /**
   * Returns a new object of class '<em>Rulegen Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rulegen Node</em>'.
   * @generated
   */
  RulegenNode createRulegenNode();

  /**
   * Returns a new object of class '<em>Rulegen Edge</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rulegen Edge</em>'.
   * @generated
   */
  RulegenEdge createRulegenEdge();

  /**
   * Returns a new object of class '<em>Report Interpreter Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Report Interpreter Spec</em>'.
   * @generated
   */
  ReportInterpreterSpec createReportInterpreterSpec();

  /**
   * Returns a new object of class '<em>Evolver Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Evolver Spec</em>'.
   * @generated
   */
  EvolverSpec createEvolverSpec();

  /**
   * Returns a new object of class '<em>Multiplicity Refinement Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplicity Refinement Spec</em>'.
   * @generated
   */
  MultiplicityRefinementSpec createMultiplicityRefinementSpec();

  /**
   * Returns a new object of class '<em>Evolver Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Evolver Parameter</em>'.
   * @generated
   */
  EvolverParameter createEvolverParameter();

  /**
   * Returns a new object of class '<em>Parameter Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter Function</em>'.
   * @generated
   */
  ParameterFunction createParameterFunction();

  /**
   * Returns a new object of class '<em>Algorithm Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithm Spec</em>'.
   * @generated
   */
  AlgorithmSpec createAlgorithmSpec();

  /**
   * Returns a new object of class '<em>Termination Condition Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Termination Condition Spec</em>'.
   * @generated
   */
  TerminationConditionSpec createTerminationConditionSpec();

  /**
   * Returns a new object of class '<em>Parameter Search Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter Search Spec</em>'.
   * @generated
   */
  ParameterSearchSpec createParameterSearchSpec();

  /**
   * Returns a new object of class '<em>Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter</em>'.
   * @generated
   */
  Parameter createParameter();

  /**
   * Returns a new object of class '<em>Parameter Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter Value</em>'.
   * @generated
   */
  ParameterValue createParameterValue();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MoptPackage getMoptPackage();

} //MoptFactory
