/*
 * generated by Xtext 2.10.0
 */
package uk.ac.kcl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.swt.graphics.Image

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MDEOptimiseUiModule extends AbstractMDEOptimiseUiModule {
	
}
