/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Property;
import org.xtext.example.mydsl.myDsl.ResourceType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ResourceTypeImpl#isContainer <em>Container</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ResourceTypeImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ResourceTypeImpl#getResourceTypes <em>Resource Types</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ResourceTypeImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ResourceTypeImpl#getPropertyReferences <em>Property References</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceTypeImpl extends MinimalEObjectImpl.Container implements ResourceType
{
  /**
   * The default value of the '{@link #isContainer() <em>Container</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isContainer()
   * @generated
   * @ordered
   */
  protected static final boolean CONTAINER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isContainer() <em>Container</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isContainer()
   * @generated
   * @ordered
   */
  protected boolean container = CONTAINER_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getResourceTypes() <em>Resource Types</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceTypes()
   * @generated
   * @ordered
   */
  protected EList<ResourceType> resourceTypes;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<Property> properties;

  /**
   * The cached value of the '{@link #getPropertyReferences() <em>Property References</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPropertyReferences()
   * @generated
   * @ordered
   */
  protected EList<Property> propertyReferences;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.RESOURCE_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isContainer()
  {
    return container;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContainer(boolean newContainer)
  {
    boolean oldContainer = container;
    container = newContainer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RESOURCE_TYPE__CONTAINER, oldContainer, container));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RESOURCE_TYPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ResourceType> getResourceTypes()
  {
    if (resourceTypes == null)
    {
      resourceTypes = new EObjectContainmentEList<ResourceType>(ResourceType.class, this, MyDslPackage.RESOURCE_TYPE__RESOURCE_TYPES);
    }
    return resourceTypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Property> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<Property>(Property.class, this, MyDslPackage.RESOURCE_TYPE__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Property> getPropertyReferences()
  {
    if (propertyReferences == null)
    {
      propertyReferences = new EObjectResolvingEList<Property>(Property.class, this, MyDslPackage.RESOURCE_TYPE__PROPERTY_REFERENCES);
    }
    return propertyReferences;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.RESOURCE_TYPE__RESOURCE_TYPES:
        return ((InternalEList<?>)getResourceTypes()).basicRemove(otherEnd, msgs);
      case MyDslPackage.RESOURCE_TYPE__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.RESOURCE_TYPE__CONTAINER:
        return isContainer();
      case MyDslPackage.RESOURCE_TYPE__NAME:
        return getName();
      case MyDslPackage.RESOURCE_TYPE__RESOURCE_TYPES:
        return getResourceTypes();
      case MyDslPackage.RESOURCE_TYPE__PROPERTIES:
        return getProperties();
      case MyDslPackage.RESOURCE_TYPE__PROPERTY_REFERENCES:
        return getPropertyReferences();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.RESOURCE_TYPE__CONTAINER:
        setContainer((Boolean)newValue);
        return;
      case MyDslPackage.RESOURCE_TYPE__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.RESOURCE_TYPE__RESOURCE_TYPES:
        getResourceTypes().clear();
        getResourceTypes().addAll((Collection<? extends ResourceType>)newValue);
        return;
      case MyDslPackage.RESOURCE_TYPE__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends Property>)newValue);
        return;
      case MyDslPackage.RESOURCE_TYPE__PROPERTY_REFERENCES:
        getPropertyReferences().clear();
        getPropertyReferences().addAll((Collection<? extends Property>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.RESOURCE_TYPE__CONTAINER:
        setContainer(CONTAINER_EDEFAULT);
        return;
      case MyDslPackage.RESOURCE_TYPE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.RESOURCE_TYPE__RESOURCE_TYPES:
        getResourceTypes().clear();
        return;
      case MyDslPackage.RESOURCE_TYPE__PROPERTIES:
        getProperties().clear();
        return;
      case MyDslPackage.RESOURCE_TYPE__PROPERTY_REFERENCES:
        getPropertyReferences().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.RESOURCE_TYPE__CONTAINER:
        return container != CONTAINER_EDEFAULT;
      case MyDslPackage.RESOURCE_TYPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.RESOURCE_TYPE__RESOURCE_TYPES:
        return resourceTypes != null && !resourceTypes.isEmpty();
      case MyDslPackage.RESOURCE_TYPE__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case MyDslPackage.RESOURCE_TYPE__PROPERTY_REFERENCES:
        return propertyReferences != null && !propertyReferences.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (container: ");
    result.append(container);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ResourceTypeImpl
