/*
 * generated by Xtext 2.10.0
 */
package uk.ac.kcl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MDEOptimiseStandaloneSetup extends MDEOptimiseStandaloneSetupGenerated {

	def static void doSetup() {
		new MDEOptimiseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
