/**
 * generated by Xtext 2.10.0
 */
package uk.ac.kcl.mdeoptimise;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Interpreter Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ConstraintInterpreterSpec#getConstraintName <em>Constraint Name</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ConstraintInterpreterSpec#getConstraintType <em>Constraint Type</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ConstraintInterpreterSpec#getConstraintSpec <em>Constraint Spec</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getConstraintInterpreterSpec()
 * @model
 * @generated
 */
public interface ConstraintInterpreterSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraint Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Name</em>' attribute.
   * @see #setConstraintName(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getConstraintInterpreterSpec_ConstraintName()
   * @model
   * @generated
   */
  String getConstraintName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ConstraintInterpreterSpec#getConstraintName <em>Constraint Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Name</em>' attribute.
   * @see #getConstraintName()
   * @generated
   */
  void setConstraintName(String value);

  /**
   * Returns the value of the '<em><b>Constraint Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Type</em>' attribute.
   * @see #setConstraintType(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getConstraintInterpreterSpec_ConstraintType()
   * @model
   * @generated
   */
  String getConstraintType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ConstraintInterpreterSpec#getConstraintType <em>Constraint Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Type</em>' attribute.
   * @see #getConstraintType()
   * @generated
   */
  void setConstraintType(String value);

  /**
   * Returns the value of the '<em><b>Constraint Spec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint Spec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Spec</em>' attribute.
   * @see #setConstraintSpec(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getConstraintInterpreterSpec_ConstraintSpec()
   * @model
   * @generated
   */
  String getConstraintSpec();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ConstraintInterpreterSpec#getConstraintSpec <em>Constraint Spec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Spec</em>' attribute.
   * @see #getConstraintSpec()
   * @generated
   */
  void setConstraintSpec(String value);

} // ConstraintInterpreterSpec
