/**
 * generated by Xtext 2.14.0
 */
package uk.ac.kcl.mdeoptimise;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Path Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ModelPathSpec#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getModelPathSpec()
 * @model
 * @generated
 */
public interface ModelPathSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Location</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' attribute.
   * @see #setLocation(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getModelPathSpec_Location()
   * @model
   * @generated
   */
  String getLocation();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ModelPathSpec#getLocation <em>Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' attribute.
   * @see #getLocation()
   * @generated
   */
  void setLocation(String value);

} // ModelPathSpec
