/**
 * generated by Xtext 2.14.0
 */
package uk.ac.kcl.mdeoptimise;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objective Interpreter Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveName <em>Objective Name</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveTendency <em>Objective Tendency</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveType <em>Objective Type</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveSpec <em>Objective Spec</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getObjectiveInterpreterSpec()
 * @model
 * @generated
 */
public interface ObjectiveInterpreterSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Objective Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective Name</em>' attribute.
   * @see #setObjectiveName(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getObjectiveInterpreterSpec_ObjectiveName()
   * @model
   * @generated
   */
  String getObjectiveName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveName <em>Objective Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective Name</em>' attribute.
   * @see #getObjectiveName()
   * @generated
   */
  void setObjectiveName(String value);

  /**
   * Returns the value of the '<em><b>Objective Tendency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective Tendency</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective Tendency</em>' attribute.
   * @see #setObjectiveTendency(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getObjectiveInterpreterSpec_ObjectiveTendency()
   * @model
   * @generated
   */
  String getObjectiveTendency();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveTendency <em>Objective Tendency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective Tendency</em>' attribute.
   * @see #getObjectiveTendency()
   * @generated
   */
  void setObjectiveTendency(String value);

  /**
   * Returns the value of the '<em><b>Objective Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective Type</em>' attribute.
   * @see #setObjectiveType(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getObjectiveInterpreterSpec_ObjectiveType()
   * @model
   * @generated
   */
  String getObjectiveType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveType <em>Objective Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective Type</em>' attribute.
   * @see #getObjectiveType()
   * @generated
   */
  void setObjectiveType(String value);

  /**
   * Returns the value of the '<em><b>Objective Spec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective Spec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective Spec</em>' attribute.
   * @see #setObjectiveSpec(String)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getObjectiveInterpreterSpec_ObjectiveSpec()
   * @model
   * @generated
   */
  String getObjectiveSpec();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ObjectiveInterpreterSpec#getObjectiveSpec <em>Objective Spec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective Spec</em>' attribute.
   * @see #getObjectiveSpec()
   * @generated
   */
  void setObjectiveSpec(String value);

} // ObjectiveInterpreterSpec
