/**
 * generated by Xtext 2.14.0
 */
package uk.ac.kcl.mdeoptimise;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Problem Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getBasepath <em>Basepath</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getMetamodel <em>Metamodel</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getModel <em>Model</em>}</li>
 *   <li>{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getModelInitialiser <em>Model Initialiser</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getProblemSpec()
 * @model
 * @generated
 */
public interface ProblemSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Basepath</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Basepath</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basepath</em>' containment reference.
   * @see #setBasepath(BasePathSpec)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getProblemSpec_Basepath()
   * @model containment="true"
   * @generated
   */
  BasePathSpec getBasepath();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getBasepath <em>Basepath</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basepath</em>' containment reference.
   * @see #getBasepath()
   * @generated
   */
  void setBasepath(BasePathSpec value);

  /**
   * Returns the value of the '<em><b>Metamodel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Metamodel</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metamodel</em>' containment reference.
   * @see #setMetamodel(MetaModelSpec)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getProblemSpec_Metamodel()
   * @model containment="true"
   * @generated
   */
  MetaModelSpec getMetamodel();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getMetamodel <em>Metamodel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metamodel</em>' containment reference.
   * @see #getMetamodel()
   * @generated
   */
  void setMetamodel(MetaModelSpec value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(ModelPathSpec)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getProblemSpec_Model()
   * @model containment="true"
   * @generated
   */
  ModelPathSpec getModel();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(ModelPathSpec value);

  /**
   * Returns the value of the '<em><b>Model Initialiser</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model Initialiser</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Initialiser</em>' containment reference.
   * @see #setModelInitialiser(ModelInitialiserSpec)
   * @see uk.ac.kcl.mdeoptimise.MdeoptimisePackage#getProblemSpec_ModelInitialiser()
   * @model containment="true"
   * @generated
   */
  ModelInitialiserSpec getModelInitialiser();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdeoptimise.ProblemSpec#getModelInitialiser <em>Model Initialiser</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model Initialiser</em>' containment reference.
   * @see #getModelInitialiser()
   * @generated
   */
  void setModelInitialiser(ModelInitialiserSpec value);

} // ProblemSpec
