/**
 * generated by Xtext 2.14.0
 */
package uk.ac.kcl.mdeoptimise.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.mdeoptimise.MdeoptimisePackage;
import uk.ac.kcl.mdeoptimise.ModelInitialiserSpec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model Initialiser Spec</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdeoptimise.impl.ModelInitialiserSpecImpl#getInitialiser <em>Initialiser</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelInitialiserSpecImpl extends MinimalEObjectImpl.Container implements ModelInitialiserSpec
{
  /**
   * The default value of the '{@link #getInitialiser() <em>Initialiser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialiser()
   * @generated
   * @ordered
   */
  protected static final String INITIALISER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInitialiser() <em>Initialiser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialiser()
   * @generated
   * @ordered
   */
  protected String initialiser = INITIALISER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelInitialiserSpecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MdeoptimisePackage.Literals.MODEL_INITIALISER_SPEC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getInitialiser()
  {
    return initialiser;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInitialiser(String newInitialiser)
  {
    String oldInitialiser = initialiser;
    initialiser = newInitialiser;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdeoptimisePackage.MODEL_INITIALISER_SPEC__INITIALISER, oldInitialiser, initialiser));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MdeoptimisePackage.MODEL_INITIALISER_SPEC__INITIALISER:
        return getInitialiser();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MdeoptimisePackage.MODEL_INITIALISER_SPEC__INITIALISER:
        setInitialiser((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MdeoptimisePackage.MODEL_INITIALISER_SPEC__INITIALISER:
        setInitialiser(INITIALISER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MdeoptimisePackage.MODEL_INITIALISER_SPEC__INITIALISER:
        return INITIALISER_EDEFAULT == null ? initialiser != null : !INITIALISER_EDEFAULT.equals(initialiser);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (initialiser: ");
    result.append(initialiser);
    result.append(')');
    return result.toString();
  }

} //ModelInitialiserSpecImpl
