/*
 * generated by Xtext 2.15.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MoptStandaloneSetup extends MoptStandaloneSetupGenerated {

	def static void doSetup() {
		new MoptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
