/*
 * generated by Xtext 2.15.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.scoping;


/**
 * This class contains custom scoping description.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class MoptScopeProvider extends AbstractMoptScopeProvider {

}
