FROM openjdk:8-jdk

COPY entrypoint.sh /

COPY mdeo.sh /

COPY ./case_studies/ /var/app/case_studies

# Install maven 3.3.9
RUN wget --no-verbose -O /tmp/apache-maven-3.3.9-bin.tar.gz http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz && \
    tar xzf /tmp/apache-maven-3.3.9-bin.tar.gz -C /opt/ && \
    ln -s /opt/apache-maven-3.3.9 /opt/maven && \
    ln -s /opt/maven/bin/mvn /usr/local/bin  && \
    rm -f /tmp/apache-maven-3.3.9-bin.tar.gz

#ENTRYPOINT ["/mdeo.sh"]
ENTRYPOINT ["/entrypoint.sh"]
