/*
 * generated by Xtext 2.17.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.mdeoptimiser.languages.parser.antlr.internal.InternalMoptParser;
import uk.ac.kcl.inf.mdeoptimiser.languages.services.MoptGrammarAccess;

public class MoptParser extends AbstractAntlrParser {

	@Inject
	private MoptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMoptParser createParser(XtextTokenStream stream) {
		return new InternalMoptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Optimisation";
	}

	public MoptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MoptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
