# Build and potentially deploy code on PRs merging into the develop or master branch
name: CI/CD

on:
  pull_request:
    branches: [ master, develop ]
    types: [assigned, opened, synchronize, reopened, closed ] # Run when there are updates to the code in the PR or when the PR is closed and merged

jobs:
  build: # Only build when not merging 
    if: ${{ !github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build with Ant
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./build/ant
        run: |
          ant -noinput -buildfile build.xml

  deploy:
    # Build and deploy when merging
    # Needs to be in a full job because file workspace isn't shared between jobs, so cannot easily refactor
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Ant
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./build/ant
          run: |
            ant -noinput -buildfile build.xml
      - name: Deploy files
        shell: bash
        run: |
          /usr/bin/chmod +x ./build/publish-artifacts.sh
          /usr/bin/bash ./build/publish-artifacts.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
