# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: PR Build

on:
  pull_request:
    branches: [ master, develop ]
    types: [assigned, opened, synchronize, reopened]


jobs:
  build:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Ant
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./build/ant
        run: ant -noinput -buildfile build.xml
