# Build a PR merging into the develop branch and deploy to the develop update site if PR is merged.
name: Dev Build

on:
  pull_request:
    branches: [ develop ]
    types: [ synchronize, closed ] # Run when there are updates to the code in the PR or when the PR is closed and merged

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Ant
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./build/ant
        run: |
          ant -noinput -buildfile build.xml

  deploy:
    needs: build
    # Temporarily removing the condition, so can test...
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy files
      shell: bash
      run: |
        /usr/bin/chmod +x ./build/publish-artifacts.sh
        /usr/bin/bash ./build/publish-artifacts.sh
      # run: echo "Would deploy at this point..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
